-- 007 — the website subscriber link (phase 8).
--
-- The campaign website keeps its own sign-up list (Cloudflare D1). A sync worker pulls that list
-- into public_request; a local matcher ranks likely voter matches for the organizer queue; and a
-- decision — human or, for exact contact-info hits, automatic — is recorded twice: on the request
-- (household_id, as before) and in the subscriber_link ledger below.
--
-- Why the ledger has no foreign keys: a voters-list re-import runs TRUNCATE household CASCADE,
-- which empties every table that references household or voter — public_request and
-- match_candidate included. The sync rebuilds the queue from the website within minutes, and the
-- matcher re-applies this ledger by natural_key (the one identity that survives re-imports), so a
-- human's accept/reject work is never lost to a list refresh.

-- Where a synced row came from. external_id is the website's D1 row id; unique per source so the
-- five-minute sync is a plain idempotent upsert. Rows posted straight to the public form keep
-- external_id NULL.
ALTER TABLE public_request ADD COLUMN external_id text;

-- The website's double-opt-in state, mirrored for the organizer's benefit: 'unsubscribed' means
-- the campaign must not email this person, which is worth seeing next to their sign request. It
-- has no effect on matching — an unsubscribe withdraws email consent, not identity.
ALTER TABLE public_request ADD COLUMN website_status text
  CHECK (website_status IN ('pending', 'confirmed', 'unsubscribed'));

-- When the matcher last looked at this row. The sync NULLs it when a row's identity fields
-- actually change, so the matcher revisits exactly the rows that need it and nothing else.
ALTER TABLE public_request ADD COLUMN matched_at timestamptz;

CREATE UNIQUE INDEX public_request_external_uniq
  ON public_request (source, external_id)
  WHERE external_id IS NOT NULL;

-- Machine-ranked voter suggestions for one request. voter_id/household_id/full-name details are
-- point-in-time copies (no FK — voter ids are regenerated by every re-import); natural_key is the
-- durable identity. Dies with its request row, by design: the ledger is the durable record.
CREATE TABLE match_candidate (
  id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
  created_at timestamptz NOT NULL DEFAULT now(),
  public_request_id uuid NOT NULL REFERENCES public_request (id) ON DELETE CASCADE,
  voter_id uuid,
  natural_key text NOT NULL,
  household_id text,
  voter_name text NOT NULL,
  household_address text,
  score real NOT NULL,
  -- How this candidate was produced: an exact contact join ('email', 'phone'), fuzzy name
  -- ('name'), fuzzy name plus address ('name_address'), or re-applied from the ledger ('ledger').
  method text NOT NULL CHECK (method IN ('email', 'phone', 'name', 'name_address', 'ledger')),
  status text NOT NULL DEFAULT 'suggested' CHECK (status IN ('suggested', 'accepted', 'rejected')),
  -- app_user id of the organizer who decided, or NULL when MATCH_AUTO_ACCEPT=exact decided.
  decided_by uuid,
  decided_at timestamptz,
  UNIQUE (public_request_id, natural_key)
);

CREATE INDEX match_candidate_request ON match_candidate (public_request_id);

-- The durable ledger of decisions. Keyed on the subscriber's stable external identity plus the
-- voter's stable natural_key; survives re-imports precisely because nothing here references the
-- truncatable tables. decided_by NULL = the exact-hit auto-accept.
CREATE TABLE subscriber_link (
  source text NOT NULL,
  external_id text NOT NULL,
  natural_key text NOT NULL,
  status text NOT NULL CHECK (status IN ('accepted', 'rejected')),
  decided_by uuid,
  decided_at timestamptz NOT NULL DEFAULT now(),
  PRIMARY KEY (source, external_id, natural_key)
);

COMMENT ON TABLE match_candidate IS
  'Machine-ranked voter matches for a public_request, awaiting or recording a decision. Point-in-time copies of voter fields; natural_key is the durable identity.';
COMMENT ON TABLE subscriber_link IS
  'Durable accept/reject ledger for subscriber-to-voter links. No FKs on purpose: survives voters-list re-imports; re-applied by the matcher.';
